version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: storygram-app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "80:80"
            - "6001:6001"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql_db
        networks:
            - storygram-net
    mysql_db:
        image: mysql:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: storygram
        ports:
            - 3306:3306
        networks:
            - storygram-net
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - storygram-net

networks:
    storygram-net:
        driver: bridge
